modLoader="javafml"
loaderVersion="[37,)"
license="Not specified"

[[mods]]
modId="better_ores"
version="1.0.0"
displayName="Better Ores"
credits="Credit to MrBloxMan43"
displayURL="https://github.com/RandomKittenCat/cats585oresmc"
logoFile="logo.png"
authors="MrBloxMan43, cats585"
description='''
Adds more stuff and ores!
'''

[[dependencies.better_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




