modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="better_ores"
version="1.0.0"
displayName="Better Ores"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="colin, MCreator"

[[dependencies.better_ores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




